### ISSUE TITLE
Using images in headers and footers html

### ISSUE THREAD

**Issue by PBoog** [MaxMelcher/AzureDevOps.WikiPDFExport#111]
Is it possible to reference an image from the .attachments directory in the header and footer html?
I have tried a few options but so far no luck. Ideally this should work on the same path that is used in the markdown files.
For example:
```<img alt="logo" href="/.attachments/logo.png">```

Maybe I'm missing something ;)

**Comment by MaxMelcher** [comment]
No, I doubt that this works locally because the rendering engine does not support it.
You can data encode the image and put it in your html template, eg with this website https://www.base64-image.de

Let me know if that works

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Pieter Boogaerts ***@***.***>
Sent: Thursday, June 16, 2022 12:59:44 PM
To: MaxMelcher/AzureDevOps.WikiPDFExport ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxMelcher/AzureDevOps.WikiPDFExport] Using images in headers and footers html (Issue #111)


Is it possible to reference an image from the .attachments directory in the header and footer html?
I have tried a few options but so far no luck. Ideally this should work on the same path that is used in the markdown files.
For example:
<img alt="logo" href="/.attachments/logo.png">

Maybe I'm missing something ;)

**Comment by PBoog** [comment]
That works like a charm, thanks!
