### ISSUE TITLE
Links with Anchors

### ISSUE THREAD

**Issue by mcalsada** [MaxMelcher/AzureDevOps.WikiPDFExport#26]
Links that contain anchors to headings is not supported in an export. Documentation of this support can be found in the [Azure Devops Markdown Guidance](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#anchor-links)

Example Link
`[Complexity](/Skills/Complexity#lvl-1)`

Snippet of Complexity.md
```
# Delivery & Complexity

Getting stuff done. The level of complexity of tasks that you can undertake and the scale of code that you can write to a production-standard.

## LVL 1
```

**Comment by MaxMelcher** [comment]
Let me check how much effort that would be - of course, would appreciate a PR.

**Comment by MaxMelcher** [comment]
Its a little bit tricky...

Because we render everything in one page, all anchor links are "global". 
Deep linking, as you showed with the example link `[Complexity](/Skills/Complexity#lvl-1)` would require that we rewrite all anchors that are added by markdig so they contain the entire hierarchy, e.g the target link would need to be **#Complexity-skills-complexity-lvl-1**. Duplicates would be a challenge, too.

My calendar is pretty full right now - not going to implement it in the near future, sorry. 
PR welcome.
